services:
  jenkins-agent:
    image: localhost:5000/jenkins-base-agent:latest
    group_add:
      - ${DOCKER_GID:-1001} # To be updated with your actuall docker group (run getent group docker)
    environment:
      - JENKINS_URL=http://host.docker.internal:8080
      - JENKINS_SECRET=915473672d1d469e06e0911db38977cab04324ddd42b698ae1bea8488e0d01a9
      - JENKINS_AGENT_NAME=agent
      - JENKINS_AGENT_WORKDIR=/home/jenkins/agent 
      - JENKINS_AGENT_LABELS=dev
    volumes:
      - ${PWD}/agent:/home/jenkins/agent
      - /var/run/docker.sock:/var/run/docker.sock
      - ${HOME}/.docker/config.json:/home/jenkins/.docker/config.json:ro
      - /tmp:/tmp
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
